### PR TITLE
Final update v1

### PR DESCRIPTION
**Pull request by charlesmaddock**

### CODE REVIEW

**Comment by charlesmaddock** [comment]
MVP is done, great job team! @sakerhetspolisen @Nautman @Zigolox @kelszo @jugswe

**Comment by sakerhetspolisen** [comment]
Should we create a nice README and a pre-release maybe? @charlesmaddock

**Comment by Zigolox** [comment]
> Should we create a nice README and a pre-release maybe? @charlesmaddock
Would be nice to have. One could copy digitalungdoms readme and change it up a bit.

**Comment by charlesmaddock** [comment]
> > Should we create a nice README and a pre-release maybe? @charlesmaddock
> > Would be nice to have. One could copy digitalungdoms readme and change it up a bit.

Good idea! I can fix this.

**Pull request merged**
