### PR TITLE
New interactive question: React to search results

### PR DESCRIPTION
**Pull request by sakerhetspolisen**
Left before able to merge:

- ~Write content for 2 more search queries~
- ~Fix bug: Content flickers on window resize (use useState)~
- ~Optimize for all sceens (add margin-bottom for laptop size)~

### CODE REVIEW

**Comment by Zigolox** [comment]
There are still some

**Comment by sakerhetspolisen** [comment]
@Zigolox I wasn't able to reproduce the bug with the score being a float with many digits. However, I'm creating an issue for the icon changing for half and quarters of a star etc.

**Comment by sakerhetspolisen** [comment]
@charlesmaddock It seems like we have a new `id` system in the constants.js file that I'm unaware of. Could you please resolve the merge conflicts in constants.js?

**Comment by charlesmaddock** [comment]
@sakerhetspolisen you really outdid yourself this time - amazing work!! I found no issues whilst testing and I'll be merging this with a dev branch soon that will contain all the final PRs. That way we can show SSF all our work before pushing to production.

**Comment by charlesmaddock** [comment]
Merged into final-update-v1.

**Pull request closed without merging**
